main:
  - name: Science
    url: "/tour"
    weight: 10
  - name: Research
    url: "/event"
    weight: 15
  - name: Projects
    url: "/project"
    weight: 20
  - name: Publications
    url: "/publication"
    weight: 30
  - name: News
    url: "/#news"
    weight: 40
  - name: Team
    url: "/#people"
    weight: 50
  - name: Visualization
    url: "/viz"
    weight: 55
  - name: Explorables
    url: "https://www.complexity-explorables.org"
    weight: 60
  - name: Contact
    url: "/contact"
    weight: 70
  - name: Jobs
    url: "/job"
    weight: 90
